### ISSUE TITLE
Adopting this plugin

### ISSUE THREAD

**Issue by micgro42** [MrBertie/yearbox#7]
Hey @MrBertie 

as you offered in #6, I would like adopt this plugin and take over its development and maintenance.

So, with your permission, I would change its page at dokuwiki.org to point to my fork and indicate the change of ownership?

If you wish, you can archive this repository, indicating that it is obsolete.

Does this sound good to you?

**Comment by MrBertie** [comment]
That will be acceptable Michael.  Good to see it going to a good home!

**Comment by micgro42** [comment]
I've changed the info on the dokuwiki.org page, thank you :)
